### ISSUE TITLE
Elm errors for perfect valid Elm code?

### ISSUE THREAD

**Issue by hipertracker** [rundis/elm-light#15]
I use the latest stable Lighttable  on OS X  and it shows Elm errors for no reason. The code is valid. I can even open it in the page. It does not make any sense. I created [a screencast to show the case](https://goo.gl/PH0oqj)

**Comment by rundis** [comment]
Hi !
- You need to write module, not package in the module header. 
- The type annotation for greet is wrong (it says great).
  .. so no the code isn't perfect valid elm code.

which version of elm-light are you using btw ?

cheers
-magnus

**Comment by hipertracker** [comment]
The latest stable, both Light (0.8.1) and elm-light (0.3.4).

**Comment by hipertracker** [comment]
I think Cmd+Enter captures output from elm-repl instead of Elm linter.  elm-repl doesn't understand type annotations.

**Comment by rundis** [comment]
Ah didn't pay attention. 
- Correct. Eval is only a thin wrapper around elm-repl
- And yeah, evaluation type annotations isn't supported by elm-repl
- The first error you get is because of using package rather than the correct keyword module

So I don't really think there is anything wrong with elm-light in this case. You might argue that it could have told you that evaluating type annotations isn't supported, but that would be a separate issue if you think that would be important.

tx for the detailed explanation though! Very few bothers to provide that much context when reporting issues.
