### ISSUE TITLE
Improvement: Autocomplete should provide suggestions from my sources and current file 

### ISSUE THREAD

**Issue by dusky3** [rundis/elm-light#27]
Autocomplete works fine for the elm related stuff (from packages), but it dosn't suggest any words (strings, function names,...) that are already in the current file.

**Comment by rundis** [comment]
Yeah I know. It's a know limitation because I'm using [elm-oracle](https://github.com/ElmCast/elm-oracle) which uses packages docs to infer autocompletions. 

If there's any consolation I'm working (hard!) on creating an elm parser that will expose an AST in json for your projects elm code (and any 3rd party deps if performance allows). This will allow more and obviously better autocompletion features. However there is still some legwork to do, and I think I'll address #25 and #26 before getting to this issue.

I took the liberty to rename the feature.

Tx for the report and  hang in there, I'm confident the AST approach will reap some pretty awesome benefits to the plugin :-)

**Comment by dusky3** [comment]
Good to know that you are aware of this issue @rundis. I find LightTable with the elm-light plugin to be the absolutely best choice for Elm development, so I can easily wait for any new feature. Thank you for your hard word on this amazing plugin.

**Comment by rundis** [comment]
This is now implemented in version 0.4.0

**Comment by dusky3** [comment]
Thank you @rundis
