### ISSUE TITLE
Bar at the left overlaps text

### ISSUE THREAD

**Issue by MarcusE1W** [rundis/elm-light#40]
At the left side of the editor window I have a coloured column/bar which overlays the first characters in the editor. 

Looks a bit like the line number bar but without the numbers. 
I have turned line numbers  off in the settings using.

So I don't know why this bar is therein first place and then it overlays the text.
Any help is appreciated.

See screenshot:
![lighttable-bar2](https://cloud.githubusercontent.com/assets/26278354/23707182/50dec100-0409-11e7-9524-935e6fb2255f.png)

**Comment by rundis** [comment]
Wow that's an odd one. Does it persist if you close and open the editor window again ? I'm thinking there might be some bug with how the gutter stuff is implemented in Light Table.

**Comment by MarcusE1W** [comment]
It does persist. I did a few tests to see when it happens exactly.
- It is a problem when you open a new file (for me it happens only with .elm files, I tried html and that was not showing the bar at all)
- If I open another tab (e.g. browser( that then covers the elm file and move back to the elm file it is slightly better but not resolved
- If I then turn line numbering on then, well numbering is on and the overlay disappeared completely
- If I turn numbering off again it is fine as well and the original bar is smaller (only the brighter part is visible)

I am of course not sure if it is related to elm at all, it is just the only language I really use.

I have a few screenshots to show how it looks:

When I start lighttable and open a file the bar overlays some of the text:
![lighttable-bar5](https://cloud.githubusercontent.com/assets/26278354/23766039/3dd1df50-04fb-11e7-8463-b583b1bebdd7.png)

After opening an additional browser tab and then juming back to the elm prog it is only a bit overlayed now
![lighttable-bar6](https://cloud.githubusercontent.com/assets/26278354/23766131/8340ad00-04fb-11e7-9486-677cd5286e47.png)

After turning the line numbering on it is ok
![lighttable-bar7](https://cloud.githubusercontent.com/assets/26278354/23766179/a16822b8-04fb-11e7-9a81-22e88a7b2938.png)

Now turning the line numbering off again is also ok and there is actually less bar.
![lighttable-bar8](https://cloud.githubusercontent.com/assets/26278354/23766207/c434c0c6-04fb-11e7-9c27-a151c0d696e2.png)

When I open another elm programme there is no overlay, but this bar is wider again. The bar in the previous elm window stays thinner.
![lighttable-bar9](https://cloud.githubusercontent.com/assets/26278354/23766252/f01907ba-04fb-11e7-9151-8711cf6f309f.png)

When I open a different source code there is no bar at all. (I only tried with html and C)
![lighttable-bar10](https://cloud.githubusercontent.com/assets/26278354/23766294/1353861a-04fc-11e7-8bc8-d2ef8ffaaa63.png)

So there it is. The workaround for now seems to be to turn line numbering on or off.

**Comment by rundis** [comment]
Thx for the detailed description !

Ok this is what it should have looked like (depending on skin/theme).
![exposed-gutter](https://cloud.githubusercontent.com/assets/399197/23766950/06e5d620-0507-11e7-937e-c0f0856383a3.png)

So it seems that the combination of your skin and faulty behavior/css the gutter doesn't adjust the remaning editor size appropriately. I'll need to look into what can be done.

In the mean time you can remove the exposed indication gutter by adding the following to your user.behaviors file:

```clojure
  [:editor.elm :-lt.plugins.elm-light.gutter/show-elm-gutter]
  [:editor.elm :-lt.plugins.elm-light.gutter/elm-gutter-exposeds]
  [:editor.elm :-lt.plugins.elm-light.gutter/elm-gutter-exposeds-mark]
```
(the minus sign before a behavior (think event if you like) will disable that particular behavior.)

You probably need to reopen any open editors to see the effects. But once that is done, from then on the elm specific gutter should be gone. 


It's a shame it's misbehaving, cause I find it kind of useful to see if something is exposed given the context I'm in, rather than having to scroll to the top of the file to see the exposing declaration for the module 😢

**Comment by rundis** [comment]
Btw what skin/theme are you using ?

**Comment by MarcusE1W** [comment]
Thanks for the help. I am using rubyblue.
You are right, it is probably linked to the skin. i have changed to "default" and the bar is entirely gone .
![lighttable-bar11](https://cloud.githubusercontent.com/assets/26278354/23768609/87feb176-0504-11e7-8038-d3cfd13c0905.png)

**Comment by rundis** [comment]
nope it's there (but for that skin it has the same color as the editor) cause I can see the @ sign to the left of main ! 

Anyways, I have a feeling that the problem with the gutter not adjusting margins correctly is a generic error. I seem to recall having seen it myself when I think about it.
