### ISSUE TITLE
Auto-complete doesn't care about the module

### ISSUE THREAD

**Issue by thisredone** [rundis/elm-light#8]
When I type `Resul` the auto-complete tells me things like `Result.andThen` and `Result.Ok` which is great but when I go further, as in `Result.to` expecting things like `Result.toMaybe` I get completions from `Basics` like `Basics.toFloat` or `Basics.toString`

**Comment by rundis** [comment]
Made autocomple module aware in 0.3.2.

... But it's still acting up in some cases because of the buildt-in autocompleter widget in Light Table is caching stuff it shouldn't. Think I need to write a custom autocompleter widget to gain full control, but I'm leaving that for another issue and another nite !
